---
- name: Assert Fedora version
  ansible.builtin.assert:
    that:
      - ansible_facts["distribution"] == 'Fedora'
      - ansible_facts["distribution_major_version"] | int >= 43
    fail_msg: "This role targets Fedora 43 or newer."
