---
timezone: UTC
locale: en_US.UTF-8

primary_user: michael
primary_user_shell: /bin/zsh
enable_passwordless_sudo: true

enable_auto_updates: false
enable_firewalld: false

_arch_map:
  x86_64: x86_64
  aarch64: aarch64

_github_arch: "{{ _arch_map[ansible_architecture] }}"
