---
_pyenv_build_deps:
  - make
  - gcc
  - patch
  - zlib-devel
  - bzip2
  - bzip2-devel
  - readline-devel
  - sqlite
  - sqlite-devel
  - openssl-devel
  - tk-devel
  - libffi-devel
  - xz-devel
  - libuuid-devel
  - gdbm-libs
  - libnsl2

_terminal_packages:
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - foot
  - tmux
  - neovim
  - fzf
  - bat
  - btop
  - fastfetch
  - zoxide
