---
all:
  children:
    workstation:
      hosts:
        fedora-hyprland:
          ansible_host: 192.168.64.6
          ansible_user: michael
        kali-hyprland:
          ansible_host: 10.211.55.28
          ansible_user: parallels
        kali-i3:
          ansible_host: 10.211.55.30
          ansible_user: michael
    hyprland:
      hosts:
        fedora-hyprland:
        kali-hyprland:
    i3:
      hosts:
        kali-i3:
    kali_linux:
      vars:
        ansible_group_priority: 10
      hosts:
        kali-hyprland:
        kali-i3:
    pentest:
      hosts:
        kali-hyprland:
        kali-i3:
    vpn_clients:
      hosts:
        fedora-hyprland:
        kali-hyprland:
        kali-i3:
