---
all:
  children:
    workstation:
      hosts:
        fedora43:
          ansible_host: 192.168.64.6
          ansible_user: michael
        kali:
          ansible_host: 10.211.55.28
          ansible_user: parallels
    hyprland:
      hosts:
        fedora43:
        kali:   # uncomment to enable Hyprland on Kali
    pentest:
      hosts:
        fedora43:
        kali:
    vpn_clients:
      hosts:
        fedora43:
        kali:
