---
_sddm_packages:
  - sddm
  - libqt6svg6
  - qt6-qpa-plugins
  - qml6-module-qtquick-controls
  - qml6-module-qtmultimedia
  - qml6-module-qt5compat-graphicaleffects

_i3_packages:
  - i3
  - i3blocks
  - i3lock
  - rofi
  - feh
  - xwallpaper
  - picom
  - dunst
  - xclip
  - xss-lock
  - alacritty
  - arandr
  - autorandr
  - maim
